### PR TITLE
Fix 2128

### LINKED ISSUE #2128: Error when inserting node during render: "Failed to execute 'insertBefore' on 'Node'"
## Expected Behavior
When rendering there should be no errors and all the elements should be rendered in the correct order.

## Current Behavior
When [inserting a node](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L469) during the render process, if `nextSibling` is not a proper child of `parent` then the following error occurs:
```
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```
This happens in the following situations that I have found. In all cases `nextSibling.parentNode`  becomes null:
1. In `updateNodes` when the keys between the compared nodes match while traversing the nodes backwards.
   * `nextSibling` is assigned to `o.dom` of the element that got updated. `o.dom` can be removed from the dom if the tags are different, causing `o.dom.parentNode` to be null. `nextSibling` is set to `o.dom` causing the error if `insertNode` is eventually called with the same `nextSibling`. 
https://github.com/MithrilJS/mithril.js/blob/ec43ca089c67b1af3bc3f729d18dd5eaa283ea53/render/render.js#L314-L318
https://github.com/MithrilJS/mithril.js/blob/ec43ca089c67b1af3bc3f729d18dd5eaa283ea53/render/render.js#L322-L328
    * Additionally, this can happen when there are more old nodes than new nodes. In this case the call to `updateNode` the next sibling is determined by calling `getNextSibling` with the old nodes. If an old node exists but was removed it could return that node which would be set to `nextSibling`.
https://github.com/MithrilJS/mithril.js/blob/ec43ca089c67b1af3bc3f729d18dd5eaa283ea53/render/render.js#L462-L467
2. In `updateNodes` when keys do not match between compared nodes while traversing backwards: 
   * `nextSibling` is set to the node that gets created. 
https://github.com/MithrilJS/mithril.js/blob/ec43ca089c67b1af3bc3f729d18dd5eaa283ea53/render/render.js#L328-L330
But that node can be a fragment and `parentNode` for a fragment is also null.
https://github.com/MithrilJS/mithril.js/blob/ec43ca089c67b1af3bc3f729d18dd5eaa283ea53/render/render.js#L92-L102

Those are the only cases where `nextSibling` is set to a value without a parent as far as I could tell.

This commit: https://github.com/MithrilJS/mithril.js/commit/02aab654f0b1b02e35234fca9dc47c306ba62bd7 removed the check for `nextSibling.parentNode` inside `insertNode`. This is causing the underlying issues to not be hidden. Whereas before the commit the error wasn't present, there still was issues with ordering of the rendered elements since the check caused `appendChild` to be called instead of `insertBefore`.

## Possible Solution
In the first case above the old element `o.dom` was removed. Then it's assigned to `nextSibling`. Instead I think `v.dom` should be the next sibling since it is the element that is on the dom.
```javascript
updateNode(parent, o, v, hooks, getNextSibling(old, oldEnd + 1, nextSibling), ns)
nextSibling = v.dom
```
`getNextSibling` should be updated to not return a dom element if it doesn't have a parent. That way it doesn't set `nextSibling` to a removed node.
```javascript
function getNextSibling(vnodes, i, 
    for (; i < vnodes.length; 
        if (vnodes[i] != null && vnodes[i].dom != null && vnodes[i].dom.parentNode != null) return vnodes[i].dom
    }
    return nextSibling
}
```
And for the second case the created fragment is set to `nextSibling`. Instead `v.dom` should be used since the fragment itself isn't a part of the dom. `v.dom` is already set to the first child of the fragment.
```javascript
createNode(parent, v, hooks, ns, nextSibling)
nextSibling = v.dom
```
I did some testing with the above changes and it appears to fix the error successfully and keep the correct order of elements. But I'm not too familiar with the code so I'm looking for some feedback.

I'd be happy to create the PR with these fixes if they're correct.

## Steps to Reproduce (for bugs)
Simple steps to reproduce the first case:
1. Render node:
   * Tag "div" with key "2".
2. Render nodes:
   * Tag "span" with key "1".
   * Tag "span" with key "2".

Code snippet: [Flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvAekYAIBRDOATxbrhohoA5gB00zFmIlU0-FuSwAHFgF4WAChoYhJFmkoATGAEpVAPhbJe23cBYBrGF0QsABo64ASYPqMBfVxY-XVc+Gm9fGACWAF0AbjEpVhk5ACd6I1SAOUN4VQ0tHRZ8Esi4UxULLHx0tEz1A0pyAFccWnwAI0MuXTL8LAxFdUjzFix1EvwFIcLe3OMF4wS0JJZazJyjOHUREAMIADdd3QAGEgAmJdX1mGzc7d24RQwVkF0ARgurlbRqm9SGk1WvQaJ1urpkGIWGMdmhofDJHtDscoQiWHYPC5duddkESKiEbswjiQKjjGIYt8xH8MrdAS02qCugYepZUeMCfDHs9Xvi4WiMU4sSB3rjgpzoUT4DRRaT+cY+dCOfzCSAni8USr4YLnIiSXiJYjibsyRSlm81TBYOQBNQEIgQAB2RDnAAcID8MTIUEE9ntqBAmBweCwEBoAAtUtALc1UlA8OGaDRFHBEMxmmhFPYhFNKFhGKGI1GoAABd74csAVgLYcj0CIpBANC4ilwDrg5CjihoFueNHI4fgSGQI7OIBgBl0IC9yAAtJ8QAB9fgYOguDNGSBoCdTmcL6ckZBjmAHegH86Okiui4nAAsN9vM6PZFSlFbqWbYgPyAXYAzNogagWAgOA2CUZt1EoDpCBgG1TGARIaDAShUg0A4MFQjxgLhKCYLg4CwA0cNOAAeQAdzQKYMCgKBIOg2CaF0DwFjWGAaFjOEwGouAYEQ9J2NSOEaFSZpeLQPwvxnMc-zQADqAPd4ADYSHec5lNdABOc4ry0p8xzgKYoE4OBJMPBcRAEQj1AAQhAsDuy4dQVzofBV2E8oWAAMk8lhbNA8DHLc1JyngxCLPQ1DtzIgBBJNgvyYAJJWGgLOQgEIocJxsJYIKPIQ5KLIsiArOIuByMo8hqNo3KmKcFj8sKlKmqi2L3OQDwYnyXL2qcGIwqapLGsGprcvyFq4pM5Kku-MdUpQtCMAU5TzhOS93ldStlPWza9LIGA8NtNByXE0yfzIAAFV9Qx487KCgLhIBo-BFFfGhKGbVt8C3KqeDUGS5LQdRKpojoMHIexQuS-iON4cMQPwCN6FhRr-sO9R0KgUTIcaizocElhLrzECYFu+7HqgGp4Du08gaq0HwfUBYEcHQHUcAwHsaaxq8bhDHRP6iy-GOoa+RR-80fSThqE57m2JhwnrpJu6HugCn0jgamYFpkGwfsRnjGZpG2eoRn0QFpqeYJq7idJlWnvSA71EljWjuWHGaCF-rhuO6apIu62buVsBz3vABmStKxIRTb0rT5o9j3bwEECddlMb8FwapqZrIMjBEaMj8HOpabxIR0NLvUvy8fQ9nxABWbaD1XTvMj2WCtHiCI0azc7qSgC-rnjnte96WxgL7BB+mWaB7-PC4DseXvekfPu+mjfqtonA7J1Wh6Xj6x9X+7EN9w9ZpoDKB6V+6D1D7T3gjyvQ9Dx-Q8TrcU5ANO9zITOLOzkAhBQCgtRQuxcVpXneOXCB5dE6Nxos3Mggs25QA7sVLugDgEU0vrvN6+9x6YDXlPDBoMsHzxwcvA+E8175Evrbcm5C8GHy4MfU6Z8L6vmLu8UOGkrznAvLwi8idU5iAyoub884yDum-iADS-98iowUmtS8GlVLKRUWpROIIIDcQQaSLmlkNAYSEAZAQOBKDNBoKYAAHpGBGEAzEWK6qkYxdiHEpTQP-d2aUNDF2jipe+t5rzvACa6IR+iipWXEfuaRRiDIwCscJMGNBfIqDUPExJNoWAAB8sksH-uoGxqR8ArmLree8qkTiujWitKpYT3ZRLIN49GGFMo8EEKxJ4doTBt1SK+VIPUuAxHTntXpKFcxGHyIU4pWh2KTXdvMugoyinq0UF0uRahUgHjKSQSsz9VJPx4fs7hicVlrJnBIkAAyhl+zlAs+pXpzifCUipc43CnmvJUYnA4EByAwHyGI85C4pFmTILIm56gZ59zIF6d4SiVIxw0kEhFoSa5jkKH1KauiLLMDgC8MMPABywXsLwSgLB9gdnMakbQfzWxvlgCwMAV0yWUEEEINwBxIjTNXH8tQkxXCIWNnCQl4MADKMytYctyLoFCEAhBUKnmg9GnLnJ-OsqklgMq5UENMEWPuegYBkXYEsnYIBXCSqMFyuggQsDNDkPoZJHQ-lYEMMVCAH9hYe0QswHIa5YZ-PDJQSgxKQIsGeHAHiBgcpwD9W4CMIFAhGOBLQElOUaJ6sXlYrgrK-VesYImxk0bc4RnMck9IABHZoEAozCBygy5oNEcq9IwDwKqTRVzsxTY0FgGt8AsAAJLJO4pQXNWhHDRowAYdCtBqUasIojBlSSY0tF6SCdlkRAghvnZAYKg7nFJuSYIXNVUWA+jALBLg5B6U4GLQYAyArxYduBlAAAEoGvW5rum-3Pi0zVVD8gfstWJRqwkeBftxnLfGcaDKDEUPdSCUYtXUV0PmkE5QvYMqofdM2BUmrCvsGK7lSqpUaoQ-Kr2LCPE3OxYwTsMBVy+PAffE4boVKVmYyi0cZBni1EYiwD9vQGkgGGWqATNz0kiogB0H0wgPX3JILfeTW1FKQMjkpFTJzeacsaFgCjwnwotNWeGyTsBzoYVQwlSq3Z2bCi0FJ3ibw-UTpsxgOzxxeDMl1ESFzsA3NIUDTQZzrmHPCRsx53z4YbOpF8wYSLbmqBQCEK+ZoihAs+Yc-F4U8XEvmMULsE+tdUoPqArR7lN874qJUopRSlTKvVY47XAAMuobjIJdD8eE3oOA0LT5kH1QkiTUnWWQzK4pyrrpmNjeY4nDFjVBMZRa7Qd4FnBiHVS-Z3QiMnNGm8+t9z3Q1u+eQu9A7wXUihe6OF2LwWYtGii+lu62Xksnd0BlxEWWku5Y9MJiQ9qWC2uzfOxe75Q1meTQMMdS64ZQEjVaGAjInKmCnSBcM+B+oSARBlfYBx8iNAZCCKYks6BsFgPD3YWPhE4fR-CLH+BBDblSM+gAKgAWQa-kXYAAeGgBgzAQA54wbnZguc88IPzwXJpKesARCkO6Y8gFCAaIcWnaB6dM9Z7JmgEhZyzgsLsCAhA3P6BYMLiw7S4CysTKjnDGU6BKHyJ4XHBO6NE5JyCZrlAjN2dMzxhANzkADB7DCysl43RrUUppVT4eNKVkTuToT0jjCeJw3NlptvlBqAd00J33Lidw7dwtmUx1hOKtkKodVuxEzJjTIwMitf8BkVDvgFCQhGArROCcRgcADiiE-th92afleq5Z2ztQnOu9sqsVgKAsgVAiDnyASvKXmC14Lg3pvzjW-t47+PufuwzC4gANR8c5QOaABhagsCP5zzv3f9+3P0Wn-IA-t38AAMJQ4MOh9ufzM6eKanQA8NjFSV0LaR0SBcpMAjSauTjEAY-XIKYD-WoLFAaVhRBJqADbTJ-XAL0BTUOUA7hCAggupT1SjQ8C5RqADZccVf9ZVcVVAvRCJG+S8IJDSZTFgtgxOBrYqc9S9CVTlQTAFHrNUcVNrSIXQANG+Z+BTSBRSVglSVg1gk5AYH0AALy1jm05SoO5XwG+QNWEyfVfSDX-iohoiVUkIuHKQ0kdGq3kOsJOETifSIwtRVWEx0LdTIn-lEPmA10VRG1DjWisMdACKCMdCEWSnTEUAMG5UQm+wACpYjEIWBYiWASxuNsB0Rc9GQskAAxKlIQRkPwEHHjFgWcGNAvZBPPWgRI5I1IjCdI4AAANUiGQE6lyTQHrSgEKLukjVKPnR9DkEoEIg-WjUGJjSMn4BODcH+EZkCCfQZRQmqLRCWOWJWLRCgyKOSVGPnWEhgCA2SRqLSKwHRCaNyBaOyT0A6MKOGJKKjRyi6FPF0A6EcW8XnWXWKNcGmOMFmKqitwsiSJSMOPRGyKKzQBaMKIDSDWjVKJeBynIAZHrVXHmlGMMxoFnH+BYAhL9A0GoBKzoEYGoGSyiLoA9X+NqKpSOOAEyNXTaMuL6xoAG2kzZV6MHDpMmIABESJmc9BchO4yIYAABydIMlOjRklgItcMHKRY1Y6UmUlYxlbQRkWGVcYCaNX7PozgGgSYsMOHbKMMOZfY2Uw0o0gvRYsk+o-k8ffk84-kgPcMK03JMVatNlGkmiQo2QUwZkv5N41dAADVZz0GwHgGeF+V0DQReGYWSlJJ5mjQOBZU-0jNiMYFzRYEZzhmjUFTJWKjAHHTqBB37EHGjX6JoBGKGLKEePeglI8AnBylzIzCrIMF+M1yTPCNYAAHU-lc4aJEBc1kzyxhSOwoxHVgJiyWAhB6BbhqJu1hJmgbRYw9iJBzhe1kIWgRihIWT9gwBCJqIhAZUIwji3xTEIAVD207RkzG9MyOxbVo0OSuSRg3wJzDo70WyWAABiF8lgEiU8VIXQsibsls5M1Mv5Qk7lTYeAU2QVP86jG4owbiMU2sXgKMb5ScyqHifUrXYUxZUMbcQtQcRGVCPokCEcszVpas+aOspwFOZ86EdQV-WMHjLDPkk9N9eY-Clkl-ZJZ4KtWdbktAWcdohtMoGsyNIwHUgi-gaNcirgSiqC6ENBLoCMbkrYRtICtAes3tRnEiDktCS4FgdssYZtE9blfCjARwHKSdF4QoP5LYtixdCMVcZMpUCAKxasjcwiENX7OAZLVZD8asl4SNHiJMelICedes7CksmNdiuAiZRircAwD1dC1y6NRGI4vyvMwlJKlkm8zubcCcaszQYiGgC0mNDoESZNayr0+YZM0ogYTAMcjKv5WAMAN6L81MHKJq24TMzc1lZDIUvCmASCps+EUo7oxSvIRq5JN6ViZ1U8AAfmTL+NKKilGqStJUEB4g-DmufL+JgqgDgoUuSush7OfMApPUIvHSFOoCw21KpToEjUoC-I1VkhgF0HFJrLbisV+SsyAheJZMEvaVcG6MCDsvcSguIu+XN1uuyi3UpQUu402LnXXKzKEqhpZI+Lh3upgFArgECCATfEbIkDfJYDZKzNZSOqgsAvSCKsiowG7XsVgz+VcpYr+1UoosjSLPCpgArUnNgGEAjHxubPJpZnkDzDyHnQGHaUZu3N3PDCOOBpVO7VgzDGymQljA2OjScjptPSzRrRpo6DDANjJsGpOsirhtHMoFFsjHMSEAlPkolPZpJUUFnHzjhE4CYp1vquWpymSTowHBPRPCtAxIwFPGTPnVxRwFaUXJTLTPluojImbSSpEj+W8UkurPtrluIq0XSCw0Xl+XDWrI6B4Cg2TP4BgEUH5oApZJ4hkEjVNp2sLXgvtvSBau4mQ1zMSRaryGoAasIodqdr7hdrbpZIrNuGTPkreiwFnGS0MULOoDZVdpCqcGjQDwHHeANv-OOpZLjVSBrowmSR3ItqS2tpYFttOvEuPvenHr+2UFdqAXdpjQ8CXtXBXvLo3qTqrTkFSq3v8oYnZnHTTUNVtU7RFLbi6vIDdVoAYvgohuaBPNLzIkHAuu3BI2TOdSFJkAECEGaHMVVPuDFNuD+RgFrA6rWtuEhsEDel0HSGmurMZTzBI1YlnBQkyGrPaRhOHtSFzh4mLpQkhqLPUsHB4AGB4HSAMBnL+XnXaKwEdVQlGMEsmqHJzvgAjRRqTpholKrsOhfsFtUdjAUo0Y7UaDyHrM6sIh+r+WgdgZweSSoC-PzsLqHrwthnSDHn7RBsGqeLP3HXRExA1Whz7TqHiUKP2ABgwhbVrNQuHJTVit8cjTkYKv0vzKWwXq4BLOTKWq7qfO0c9todltRsBsbSpXseVOIlPFrWXvDCW3aQkYNTXXuECC7uUv0tSEcEjU4GTLNWVXsAgBSwQtElcC0cGr7QRvwcaf4FVk9qqd+pqY6bqYKYMrlpKfoH5IdV2LhHKerMmpGoydFkGsRhbTQcJwnH5qjr+SpWECssIhGrieVLjrgDQGWeFtscjQLoivfomsjF2O7R-rtHlrDWUbenaaoYxqxpmP4Y9z+UEuIqBdPEjQzFgHDSaZaduP6bgC6Z6enJgH6cNokAHW7QDXrWeYhfeg2fifnS2E7G6cOm4uhtVv0Z+Zcwxvlt+3fDPRtEeNggwFtXEYDS4efLhvOr+SSRgeoU1sqMhtdsusLrIlJVxpTGlSQbMYwx3V4GlbVtbruoVYWOfPnXYZVcoF7T7RtKWw8rnMiZ7gkpzK4DjRrXiU+uSSEaHJprPUNQLr4G4senMaPLHmTMJqyrvPfEsexdYH8bGA92sc4DyFcGAroFApmORtcFxMxtyDjZZZQlyb+SyvvJut-t7VfT5K-J2YkHWPcveiXQjc7gkZ5OocjSclgmoFadzJVo-AlNNvKpMdTR3LXuowrp0ebY2OpcRs3PkDopBCutkFIZwaUv-HrbDHZh+l0FgAnQB1WvDVEjQtYB9FMpfNhRUWRu3Y0gPd7T0pysjXkfMYGB8tQgZccWLQ7gscfLFIQcFYMEIE4F+TKuhzSdwaoYwCqcoDHMccmYhZqaLOyhprjqKYPTuYeZsfweeZ4H5cesFbqBDo+YuZjUloS31ZiJuQzMJJDhIFvBODwJvFDldE+BWjI-eETi8K2EE0oZ4MZM8IxLfS63PDDwsNvH8M4-8Nj3wB5qEAjHo6iqHBuQ12-wI+eXOFvEUkdGvGk9k-qzPgsm-z730UEzQWEwyhXA-HyDOGFqwGdTQAa3oEE4lLUGZ1XBRywvyW6P49M4UvY6jm0gU9dHk5k7c744E6E8BV61SRUGE261rhE4MnPDOFhQsMdFvAo9vCi+o9RTIHs95vDET189gLA3QIwkC7kRAgAFUWauBzxQDIvg8SvQiEv79Zs0u-5cOUJBMFpUIIA9O4hgJjcQv+PhN1AWudPkkOcDOjOGt-4HPwwWuNPhMev-4D8D8v5CPI5ovIvXR7xpO5PoDa4p4quyCW5-5fC0vhjkAIBhNujkAJublOo1ULj4wHkeFzhrvAlXkLDXRXlE5+LdrvI8k0ujuDvpE9uTuhCzu1B+LzwKP3PFvbvQfiCNu5wW48uCvqy1A9uvuQUQBFUjvfva4Yh8BHBzxruYu3Pn5pO8fnuOivIfJBNPutOyhjutAPx-4MesJUkgeLh3Py5buWfE4y8LvLukfTAYfjG1AMWk9BMauhC7kaASrsDgD5NI5pONJQ4lvbxZfVvjwTLzZheoe0D-58tyDA8Rf9EtetuqN9FFVEe1ILh8eFfw8LDWClOyA4B8v6yOs3u7PvPzP1VhikuzP-5htqudeCtwk-NUJGfKwXOFeKsZfPkKv5p1AU9Gvxvqffexxmv3vNuyAmu+vui4-d62vhjjCeaiv5N8e2MiOLgi-7CKutgPeIxRu0vEezphDd7JvpvsMheE+0CFkUfoc-Dpe2MqsS+TgqsIemoO+DBkAxvpE0exxOp-OQvzxpfru2MoFzgF+y+YCQvR+a-rkkeevWjclUf4+p+Afie3ufv9+OeXuvfhbaBBAFJrxZCS-gkXPY5VJYEr-2ixIW+-8Fl25FFKt7-rC--FIsCaHOvxT7I9M+NPU7mXnq4vcSea-CAP9zkSA8cCEBe-oilQE28QAzWUHLxj25j8t+8fWnuIVY69Auso5CXk-Hkwh5g+LGJfnwgwHiZjMrKSCNDl3CgDa+C4Cfr1iPyfA6SDJa-jgSkJUC1IQg2TonEZILBVeWcH3kNxQR-JFUkqWfhYRL6hwTgFHXZKoMThOF4AIA9XmAPH4EDIB6qJASpBDxqDb4Zgx5GIMnDJ9dBEAUMpfhYA8Cc++g3eroB64OD3gXvU6Nr0-7qcHkIeZaLskrDycghGA2gNKmAF4C6+nAg8CJx-6PIS+RHbvkkPZ64Ca+4A1vrEMxK+4TBFwNQbeHARL8ChK-WuMIGYHWCohHAgwUIQ8G9AJeEXBIUUIfhNCY8FXBgYNhkxBcLkrEcgBekZJBdE+7pSQYLFMjhwlBRQx0MkMmGJwhACoTrBrkh4+Cbk+vDXob3dg8wcOTPC4IEMCRLdKwuwxOBxG8Etx3Yw0IaObHSC9DL02aDZIx2zQ5IVSAAJUY47ZyhtHeAAsIMROw7hMmNTu7HmyBpdqagOzqsjuiSCRqwI6HLmFkirhyhz0QEUXjWEDQFIgSK8CXzYzd8MRseAjLpwC5pcWAk-Goe4LxHyFf+S-YPoXwpGJxSiPAgYIoEC4ao2sSed2PA2jAwploj-YISEK5GJwzAagHrutykGgCMo-8UlJCJH7dEcROvEjgpiX6KRuEJfeURpCsFSjN+ug1gXX0kH-xsc8PXwDfzyGKi-Eco6OInBR5l54eNgi5G92siXC+hrKYTA8LFGH8G0x-M-h0Qv6Sj4+U3JgoR3n6yE-RB7MQVABm66DPRu9KbpINU7yC3RNEUwD1wjE4ZGoUYqyPq3p5u9MedUP4f72074toczwq4fSjUDu47oKSTnrALDG6c+RMTSvhKVKKgiKYLvUwA8PUDFigRzo4MbANtHXCZMwwt6NDilFTc3BXog-L2OjZJsjAWAnjNKjaxEDISugADlkHaGMk3hMTKUXUP6yMDOheLcxHmMY7PV5hvYxVF2NFJO8EY2gc0XxjPGzDsI61GgLGwLwbZKAuRBUm7koBzDtwG4jobMMkFnC-BSPDLo1GN529YekaB4QcAzG-R2xgo92Im3vHYD3hcAKnrvS9Asc5xnWecWxEXGfjlx3RXQFNx67rj6Sm42YZ8POGJj9EFYmgAmIWSFFkxaEGMR2IAlD8rIvPVmtkl34QSGJ0E-RNC3HFgVcJU5VwYJN07cDSJFE-scON7G-j3Y8YkceRKQR0TIInE6fuBOYhZj3YlEwccJKolyTReY4uCVOMZF8ZZxfoDCXeKXFMCBJlEwiXwK3FDD5JrcGQTxC2QRcZOagoIiEI8maJZB6kv8boJFE3IxRMTZAN0TYDnh3O2w15NL0UhRSwkZolSfV2tHHj7RYnGJmwDqDa5WBZHcYTFNk6RTRBFXb3qANF76ZUIcAXMQYHzF9CeUGgesaWJgFO9oc6UyNFWOd7Dcbi9YmsU2NyQti6pRgjoqYDe7JSexpBP3nJgqRoi1I3CaKdNM0TYShsXQhcNuIJZVTeCAw3rPZJKkCAb4t3bYbFzOBqR9ppoyJGl2GnOlck-8HToz3k7RxZee02XichfG0Bo+H3LTl7zMmLif+DQxSLshc4-Tb4icbiTHxsFjggpR3MLmSKqyL8oZJQscCFKal1A1RFyDUeZAcnaiaChgfUY0Nk4nBopjoXGYnDd6JSfINon4UIA9Fc8+Ek02TjHG2FRdWhMBBZMDPKk7jKpe4-IK2PqlH8fIoU3Mq1KhEu8OpgIrqexI0Ccz+psYzsWTLEkWR9JybB8UZIOAmTSBC4iyWUKskIzI03AmycRLmEsyVpe4kgTLK+FnTyxV4i8eBMKA89x2H4Aya1hJTPj8ir498WrPJnSI5ZE4hWZQBnGoTTJZA8yfNPVksC0puZbWbwN1kkCvByeHAu3ivA3SQC+PcPPKNNE1pgR+AbTLomlI-ZXZ-6dOXmHoKi9eZBgWcAR1K5qREUFHWQuR3Z4ZBtcP4oXmjOkQgy9oPkpicLxu4l8Lg+M4vheDvCwy2+fki5BlGmo7ZDu6yDVApB4TXdICFHGeXNIxQt8tpOY1matMLG1TARXMl0TzL8YBMrELAfmQ2UFl1jhZjY0Wb1I3kSyOxQ06WQXP94KR7u8nR0CtGnnPzE4CswTCPLsxjybkPsiEueD2Qh4n5ocWea8ni4wEI59XM6etNgKbS-x-CKTk-M0hdy3QyoirnkXhwfz7qo877u9N4H-zchF4J+LPKIWD8FklAQTMAO6L+MjAViNUWOGKRot8g4UskY6HDjLRWFO0Cru3xOmgDP5sAb+UITzlHFzu+ChoawvGxdyyO-cgBEwrS58KJedffVhnK1BZzWAH4oiV+P-TGFtMCkObuwui7484ur8CrrnOUVbS-ADcraR1ick-5exFBRaDgR4QUCLwMcWea4sTiaK1AyijrIaWzmBy2U8PIRbfNF7SShR0nKOLPIjiRKE45fZqR4OE7OChCGuYaBYoeTlJ2F1hQBZkue6uzFpvWKBYgLyj9QIoN8aXktzk6yiKl5wRONEVGna8KCmhFVPkDs5aE6AwS9Aj6Mfmy8ulZHY6T4jS6kyCx2aN7pdPxbnhtIXSqLl3KsJK8B5iwhcEeOlm+T-htBblAlFCXuxBAYYLgqy2qlaDXIE0d4crONkbKmoqnf+MBQUiqRJp42V0Pj1uXGKYC9sgSe1ibmyBoF4cr8UsGPp+Floj3WUf8uqUmKXlYhSBWTI+XZDCJpS8YXcveAHTYV0ilca8tAE9C7RwgCFcQIPGkExh4St0FRyZ5Uccl-ivJbAQKU3IsVZEpMdCtxWLc8pboGTuVxgKxsM+aXXoO6LE7mxaM4yskRtH75M8e+icXjCCuIx1LokW-UTEIVdlTxflTPTJbKoKkwEFZ-GPQIJnG4Sra4Uq8jNiu0gkc3QVSaXm52mHArg5yK3Qaiu7E6A5EkKuktSqW7lwJsN3dvECpgIWpT80OWoCSvNX9CrVmK9RbaouDlwJFjq8bKkLEKWiFwUCmwWKtrjWrSC8C5aNHlxkBqsRFXRAvQE9Vkqah1qpzs8hUHRdI4ea++M9yKCCZI17pLMYsqGW-CMuWymgK-jzCrJtwz05VdkOSXIIO4v+aROWvyi+COUB4KpPCnky4y4VQ62ONIq9YvThRjS8VG4T0LSIDCb6YwsDEUG5rcZscUdTEpgKOEAMLhaRLOo8I-yROEg8iZpxwI6rLwKgzaGHFxkmiKuH6Y9R-yRHyDSCEXVdcEIvW4zakaCzBoyApzzLVhQhZ9fAXowPIylQ68PB+og2wJISGuR9UITHFcEvpykFQdYU+AoblMDhPZQBgEKXSRCcQ0DUoJQ1lwh1QRVBav1bXHCB5+WZTl8L7UPJwuyGypBXBUHjZZlgYEtadPBVRqyA-8eyZPLRHAL28BauFQTIq5rUtAT1YTuf2kRRyVl5Ch5HfGQ3BIZO8mZTYAK4WYpRVaBDMiBFXmvDhVWwBVCmKhF1TzuDUnyJZz5ouZtgIIk+e1NKLu9T5HOCzlZ1cgdAbNAs+ze10bGCiMo3Rd-GflqAmdkuzS4AfYXLFhaMebq8-PQAi0j97CCBQLfQBrGiyTg5sAEXdAC3ur6AwWszqFobL1ijwnURqQVsBFFbEt2WuECVvhF3Ryt0W2oCloeFpbyJGUYYllpi3Gd2puo+4EVtgF7cEt9W2Lcf0p4Da01lEQWU1vNiKpLNKOaza2Pa1BavNbWsbblojCmBnNLAGbW5o80GAFtOWpbWUD22dbku9USQZbAxbmxfxv4y2FxFkG6ZDeMkQAnIWvDAKLwOq1SE-MTj7cMe3ipuWiAkBAatg32zea9x8gI8ftdDMzdzLgEQ7qgBeUCiDtMCWxwdQS0aTRuu31CtoKg+TCtHvg47VBDM2uEx3xFvd1FtknMPDtyAX9ngN8e8C9r4T8Jb4fCRlbXCEkZBhO6DdJMJgv5fpkIK65DReF2Q47Jhjy2uBOI-Qc7qAdABJLJr16bCl+v-W+IGpx2BrY8fBKnaysv7S7MhU8dCPzpV2oildgSMQXDwJHIFSpJGWVH+m63OE6CaOgec+tKQFqbudylXXcpqWoR1Y9aZJGoH0JVRDC9gEwrRG1Gcpco+AAjtlKfgnArCBfaPSzrHDpBeJgmIPfst3VCF3hqXAvoruAXzciF0XROG933ijFsNaXQQrXBVRN40AjqNKPg3MK4En44Sp+LfDY3wBvdsipHguqDQp6Q98BHDTcgr3yQHkUhZDU-AHVN6v1MBRPejVPDJ7t1qygAoevvXmFc1cvRnavvj17QrErYG0BOCKmaj-eeGAjHQC0HSpSM2qdpY1GoBJ60lOyEfUqIL5KjYEWAREcVP94RINAnOhJCDr61aY8wEmNQgxNgHWRSo-jOgIllgbM42IAaW9PstyiDSfIRe0svAUKAXjHgwkUmr3jsDMANKWlMIMO34B0NYcBaOxV8Osif7QQ9Y0wOQZq1AjLAH6GbG-rOU+TqDnUxQLanDBaCTlF+sJcHwE3cIqZByPhEInAAglU43GigP7rfTd6bkAGMPRHpe3RcCh8mRQ86trhX7p9Cii5Cnp3XipmOS+gQYrui4SK5e60aRSgbVSj5hCTpXYMTPEOCiduQhRAyJ3wBUEb4ykLjsoceTIaChSkN+AUFHjF7+Cpe3DdoXUPUNVAdenVQUOL6r6iOz3MQxoXgKtKx4YRjGn7pogB6l11EbHoYbxWeH3dFXOffATT119K91+9PUev6jyCRsuegoXIVX2KFI+DxSo6NIN66939+ygjgrrl7AKFDvRlOSuCeqwbpEhRGxb5L1037TePR--tMfU0wFu1-UYGUQdXQ26x4Oi6RIqg8DnBUDIADwLiAeFbGdjIEfY7khAg7K9xkBm9OoC2MsQeYzI5iRoHsA7Srw3hoIq8esKJwtjwmIresnLzx5QBex2AgcacDbHp+euEyECYunSJh0sBN7lsZ-AH9LDrwJHRBjhBji2Ap4ZtWGq2NtZqIWMKo1ZCcN8weUfxjcDAHfif5YTPkQ42CZADEncQJWlJPDzxOfp0tv+6oMSfZykhKuFsVE1qsAk8La45Q545AgUMgE0NgSDDSYosOIhcIDEE4-V0QNyJOTtJsk88dwJP8nFmpwVScb4wsmLxQvf47XDJMUndTIESI1Ly4RnBw4VplOROENOiyzj3BAsTAEuPQHrjIJ243yetwtJZADWDUtQviT5AtjyuGhSRDAAmpuyn8AkxoD9MBnd5+8koktjhMgnikzQdzcJHUD6c4z-AQM1YmEwomBIPwexahGWPJpVjqOgU48dTNwAfQvyLM7oEUgX8GeMKMYX4htPrqOzYC2uJYasTSYnj0iB0FRl7yCYMuMgsVuHsmPWng+eO8OI8kJ1jhVKxweriGdrM-ItYOZmgHmY8FzDiTyS-qIpPhPhbaTMJ2AfCeo47HXgsAok-qdpOCoxD6JzEzQBP1yIPAKIyOC9uD5BEpeF4DfSABhK3A+kgmE4MJk8HkrOyu1JoF9IvXRwfpimGTgubIAARTwVJBgGlw6xgTOUKBk819SvPDb4C2mZ6NgIR3T9M85AVyMhZgCoXMhFGQrLJFtAEcY9-hcbMhrk798wkw0QTBmRAO0AYA4Bw6G6cMDbANYsYX5FPEtgiXUgvyb-W9yciUpfklexNqLMksKWCSkRNZQ8JUspGq95JlCPg3COaX5L2l3iR6mGg4pmwPmZKHh3Ut0ARU32TvBZb2LWWiSMAMVFwFgDqAyzQq4OfwHcusmcMw-GSz5F8v0oodW83gAEcubQ4djcpm0AyYQORWpyflmK-RDitUmkroV9VN0UFESAAAQhWRiZeR9UhqYiork3L4NaApgWK8WUbKNQJAuXGy+Y0cuhpXw74AQBbWKZB0vSxEc5vGS8RR8Mohxs3I5e4mKoQrMAAZNUqZPBStjlICooyGmR+XJrU-DKxNdmuXbzYEgZ4eEfGstWs27VjKsqSNy30xypZqxIRXNhNJBrIJ7KNleWWkGPTXAbY2bn-iOXBMk6uvixHHOMhhOAk8a-BFcLjXlrXJiXKcIuHemho9xoqED2fixxkNdysYWRyfiIWPQixn3oFbCug6IrtKKK5GhlNoHrDmByQVdZaRDWcI0ObiR0esiPXnrcIf66YC8uLXYAwNyw6Df96hKrttFpsv7SqJWWQSV9FyxibdzKqcTepzGP5ZLPzWVjzhsxZl1QhPp6YxKfnola7pPnpruwe87ARmpi3RILAFwIKk8u+aWkXuqAD7p1tjxHCZZ4TCkuTLPp8GRVAC1vqMiYAqWoxANIanWLStmmqYXsvwwIZq2gweQYirHXjoaAXmWwWVEdBavkmnKdjNwNQCxbPlI6J1IW7QC4Il16c2ERZFxGktgw7W0aQho4ydb835obDVK24ypx7UJSNNVwD1YMCwBU7NAa1FAcMDHNzyJ1aq8yjyC-ZBACDJWjkzcAkRy7DCUeK4EfE5RYyEAPq4NXhDhlQ0xLK-pOXIa3Az0tQaS69TlqeX8AOYL5kmFuDlBjmt4P223ADuBl5aP7RQK2FPakp50dd2AKkEmLV69L8gKqNmjDDHNKwBrTiCCVnCgxlGPN5JHff3shATwZ45xGxAvFQZ+mulU5qXTrO1KZK0IOWo6iAQFx709FjtI3eJo2hTYiURCFg5+QUHh4+8fIEPYOjZ5j9L3D1AQ5tAj3PoQDxu-In5ueWDguulpEA4ftP40ykIEANQEPwn2EYo8Bgx0acMcPJid50Q73jEcp7QH1PADroBPDicfJiqUR35XvsnB8ADDtWxI4wd8OpHaj24Bo60du5FHMZzQCre3DaO-jmtqq5Y-xyW3LZRiBRWigUdvSOVyUReW9DsftBLbrucIW3E+GWwTbbjEYQFashk2pblVyJzQBZvY2YAxe289Y8kcsBtbCt3WHrc54HnW56WlpAA6yBn21Aq5us1rEuBTarIAGAB9Gmn4mnk4cVZw5U-WVlO0InKSpyzfVRpPwYhZo4a0bIBmXGAAD9BwDAFs54nzJ+iOrifFtGbmn8BBp5jfsPlOWnT5xCbNYtksmungkJp80nFtBX-DON82zsc1uiybz2zk8+XdTijWFnMzpZ20856I52TrkAwAYEbvp26A9OGm8UmKfqBLg7w-AJU90C3aeIYkip9c5WfMnxbl29tbYo8dIjobXoNgi8iF1vIYp8mFRDFMJm3Pw1LcsVhTwIt5hjCvEsKUPs7lEcuO14El70oq5vPBMeTwMj89aezX-n3EEwJs+Oe62dHAMGw9IiKfrmvnu5xZ6hkZeyCgX-L2gMs5BMrWan24ae5SoGiQvO4Wz3W5jdgHmO9nKppJ7o6vMPDWXJJyw9VdTg87KNeiXweFH7WqZ-+JLp+YRzvCfa2horwTLE46f2BIxfj0EBOiedPmXn45AEDS5wAoy-OxV9gE+ewfPnPhGBPMA8-dcghPXbz7l-We+f1OlngrwF+bB70GADwvfOQkRx+lzd++EcTRE9aRkLgk3zL8iakqR7-oWTUNj2Iz2eREdUNVr1DfEZHNpctLle2tdofn0KKFwnewPY4VbfUBa1eh7FZ+atdudPgRHMdy-zEPZDno7Bj6928kNd69adQD6-pCMuKXDmk5nHYR3cPR7lMVr1gt2dBmyRDmye5dwYFT26HF9kQTPRQNrfR60BRHA9hgL9Czvyp87pC4u8D3nvV3tvdd-JsV1nBouwSS8MB9hSx5SsaXToHnEveQeKjdGzuWS+CRAFgPbGYQzY-ENjnauUlmACcSMANWujPCAxZAkI5cJIEsCfD41fb118e30hoQrIYmhbvG9SHno6R56MnIYAY42fVVFg8L74PoKgw7W64QDqDFE+2uMquyvm6SCvglR5Fa6MseY9BiqwonESsl7QBZe-SDOuoBP3FB4SxQ0Lv0+i6xwHL5t-+JTfYffk9arAGAnHfvAFe94RQ1AU0TUeF3GRqQ44VTdjw+9QhZyLoq2H5rTeAXuY7XHSBceoPRR23XB9rhHLl97h++Mi-zVou2hEQuKlJ+o0O6rI1NsBEB-vjmvcvwXhPXIFMSaGFwIF8lf8ER6vr3DK0b88UKCKaIAmTpYTGV5qHkNSUNNThKB5qRdfKkf54YgqHq4AvnqPqtCaIuq+ELCOzOoz2QC2CGuUYA1lpE1zUAnAWuafX2QZBd6repupgbId9sZjtLmA6bs4GS9eSu6ChSNt+ECG2Av799c0VCM0ka5J81vM7zb8BG2-re9vN3s+MNGhi+ITvwecd0vzALPc3GAU0AcV+ExGAjIhXclWoCUiIQDgEMhIQULLhEeLwgYirl+jB+6D9AB6pHlaEGARpx5bJbQvxvu51H5Rk31gtN94dkRGYlih4+oHGI+71UkxB4bj5uLM-95-PexBLf0Rc+AefcTlXTF1j7ecMv485U3NKLM+0bgGnhVAnWhU+RPLuv84LA1EXJivNxYYH3Eh8E+YfNQ0osJmcfegHFoA-gJnrr4ph7T7jjbvwnJ-ALXJDvv80lFERgXQBbvuvucHHkKIYUcKLjnZ7m456UbBtzwJCjx918NsltQKq6aaADmklanDKP8Dstnqd3hHYBaV39-B5PjVTywAvOkQW6KvqchdHdvt16JjYxcBUVx3DhEfkbZGmNY9Z4GCZdU0f39xIZ1jgx9dXHGTs-C7-JyKuIvzp4Jgt+zRNNdFpDWn9i7aQu-Nr8BUBFLUTgqUdPgG+Py4CyRcHZjwv9eN1SGolqbAY1LsEXEl1I0NIc-BgALjcA1-VBqqH+t5ONebhvTY3zyeDgwprwB7NP9VncN4F2Lqa1b-V0m4kizVf+B0pRzczyR4QMdEH-gn0CGUV8uOVhRr84Ahwj9BPvBn1CdBYa2xft8yDQE-RZPPZxlxMrSw0ld3US-g1hYAX52NQTADHTv8i-Iby5tE-BfzP8OZZvxoBYAZnFj8jnKP2YCTAJyFX9yAD1BEZF-YpB4D8gC-3IB7jO4yJdYUKf38JKweAJkDTRaSzUBFwD3wuQPfBcC99wUMP0z1X1UD3JdCOcl0BkREFpCUDBMJs2kRHQb33FhoLPQOCQyXYDwwF+oTZDS56AsiBFRbgb5F+QNHfgLP9hMDMBa8hTD1GYVgkPQODwHPGOCi5DhcsxYBjAtLlMCkecwPBQvAlwKsCykGQJ78EUGn0ddgLbnVSkv0dIHH83JMAh3dYUI90-d2-OP10E-A6NTHAxfU4S0COOGThu53DGKUaMYCF3yMD1A0AUqCyAD30T4-oSwN99chBXjUggPLSGqwDA6OWFFjbDMCWxfdXDhBIOsUqh6CyAXByc5kfVggmwLeKbAq53IUOEWAtVPTDltWIU-zIhQTOtA1d1-ciUWCagniWcDTgxINcDvydc08DnA-k15Njgh4PcCYADR08p3NClkdQnYfzEoZpgr7wHkMoUGGgAIjG-Ts9x3Kwjx0FeMAhRtNYVIDElHA0AWmCjfY4I6D-AjaxPUnObHSL55uAkJKDkeYMTm83gxfw+CngtM1+DByLWFfB3oIELQBV6W+U4svQWLjRE2MSYW0hOQ4Pk0RIAKxBOBWQ0ASSwXILThaR-4fs3kRuVcBDHUbCWUOkUQSD914dcLUgU89V6ZPik5I4MdQkVtQ6RRjspXdXwXBCA1L3F9DuFUP3NR-YSBLQ5cX0CYdzg2JBOApndQAdDzZS+XWc4Qfs2g8V3fsx6pjER0IcDUTU6lUp1ARKF9C4AR0PuMfvcxBvhwuDw1jhJTHZDs8QCQ4ToB-kLEIuQugkUHyQw-brG0DEwipXzCCjLdQH9yglQOY5P9cf1jhFua8CrDjdQoxLDBMJYIIBHCKgErD1oO6SrCHpCrjaDUIRcHTCgUYTDBQahNQCoB0gR4SsDg+ZjC1CVoJfjV1UIRQP7DJEQcPxdaQKLBfU4UScMp9Nwmny5NywcsEExKwYTFDhPEOUA5M9RAYIi5qBLcL4Q+-GAjUA8Pd-mkRqgWhDgRaDF8O3h4EUvxwDMdHZG5C6BP8LdBqlL0EtBrQR8jwBFuSsBdBjwz0D8AgAA)

## Your Environment
* Version used: Branch `next`. Error doesn't occur in v1.1.6 or below because it doesn't include mentioned commit.
* Browser Name and version: All
* Operating System and version (desktop or mobile): Windows 10 desktop
* Link to your project: NA

### PR DESCRIPTION
**Pull request by pygy**
This fixes #2128, a DOM mocks bug that I discovered while fixing #2128, and removes quite a bit of code.

Change log item coming as soon as I have the PR number.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I have updated `docs/change-log.md`

### CODE REVIEW

File: render/render.js [hunk 1]
```diff
@@ -312,22 +315,22 @@ module.exports = function($window) {
...
 				} else {
 					if (!map) map = getKeyMap(old, oldEnd)
 					if (v != null) {
 						var oldIndex = map[v.key]
 						if (oldIndex != null) {
 							o = old[oldIndex]
-							updateNode(parent, o, v, hooks, getNextSibling(old, oldEnd + 1, nextSibling), ns)
-							insertNode(parent, toFragment(v), nextSibling)
+							insertNode(parent, toFragment(o), nextSibling)
+							updateNode(parent, o, v, hooks, nextSibling, ns)
```
Comment (pygy) [inline render/render.js]: Just below, replacing `o.skip = true` with `old[oldIndex] = null` works as well, and it would save us a vnode slot.

Is there a reason not to mutate the old children list?

File: render/render.js [hunk 2]
```diff
@@ -51,18 +51,17 @@ module.exports = function($window) {
 			vnode.state = {}
 			if (vnode.attrs != null) initLifecycle(vnode.attrs, vnode, hooks)
 			switch (tag) {
-				case "#": return createText(parent, vnode, nextSibling)
```
Comment (tivac) [inline render/render.js]: I don't have a strong opinion one way or another, but why'd this change?

File: render/render.js (hunk 1 above)
Comment (tivac) [reply render/render.js]: > save us a vnode slot

Not sure I follow...

**Comment by tivac** [comment]
This seems... reasonable. This is definitely the parts of mithril I understand the least though so I'm hesitant to actually post a review.

File: render/render.js (hunk 1 above)
Comment (pygy) [reply render/render.js]: Sorry, that wasn't clear. If we do that, we can remove the `.skip` field on vnodes, improving their memory footprint.

File: render/render.js (hunk 2 above)
Comment (pygy) [reply render/render.js]: The individual `createX` methods used to return a DOM node that was used in `createComponent()` and `updateNodes()` (in the map-based diff section).

This isn't needed anymore (and wasn't necessary in the first place AFAICT,  since `insertNode()` in `createComponent()` was redundant and we can get `v.dom` in `updateNodes()`).

So I made it explicit that `createNode()` wasn't returning anything.

**Comment by pygy** [comment]
The main change here is the simplification to get the nextSibling.

When processing both lists downwards (unkeyed diff, first part of the keyed diff), the bottom part of the list hasn't been updated yet, and we need to look for the nextSibling in the  `old` list.

When processing the new list upwards (the other three sections of the keyed list algo), the DOM nodes below `end` have already been updated, and we can set `nextSibling` to `v.dom` if it isn't null.

I've changed the list reversal part of the diff so that it processes the old list top-down and the new list bottom up to take advantage of that.

I've also moved the `insertNode()` calls before `updateNode()` where the nodes actually move, to take advantage of the cached `nextSibling`.

All in all, It saves us many `getNextSibling()` calls. I should probably update the comment about this to make it more clear.

**Comment by pygy** [comment]
@tivac I just pushed another commit that fully disentangles keyed and unkeyed diff.

With that, the pool stuff removed and the bug fixes, `updateNodes()` is at its simplest ever (the parts that I had a hard time to understand were actually buggy). It may be a good time to re-read it top-down.

**Comment by tivac** [comment]
I'll take a look tomorrow

**Comment by pygy** [comment]
Ok, I've cleaned it up some more, and added some comments :-)

**Comment by pygy** [comment]
@isiahmeadows do you want to be removed from the owners file as well (that was an automatic review request)?

**Comment by isiahmeadows** [comment]
@pygy [I already took care of that](https://github.com/MithrilJS/mithril.js/commit/0dbf17c6212ed1ed3830df46ae414182d5ddfdc0).

**Comment by pygy** [comment]
:+1: I had missed it.

File: render/render.js [hunk 3]
```diff
@@ -256,84 +265,107 @@ module.exports = function($window) {
 		else if (old == null) createNodes(parent, vnodes, 0, vnodes.length, hooks, nextSibling, ns)
 		else if (vnodes == null) removeNodes(old, 0, old.length)
 		else {
-			var start = 0, commonLength = Math.min(old.length, vnodes.length), isUnkeyed = false
-			for(; start < commonLength; start++) {
-				if (old[start] != null && vnodes[start] != null) {
-					if (old[start].key == null && vnodes[start].key == null) isUnkeyed = true
+			// default to keyed because, when either list isfull of null nodes, it has fewer branches
```
Comment (tivac) [inline render/render.js]: >isfull

"is full"

**Comment by pygy** [comment]
Here we go!

**Comment by pygy** [comment]
I think most of the updateNodes fixes could be backported, I'll have to review the patches (I'm quite busy at the moment though so I can't promise it'll be quick).

**Comment by pygy** [comment]
@JacksonJN actually there are some changes in the `next` branch that are backwards incompatible (state/hooks-related), and disentangling them is more trouble than I can deal with now, so this will go in v2.

**Comment by JacksonJN** [comment]
@pygy Is v2 currently planned or is there an ETA?

**Comment by pygy** [comment]
We're actively working on it (there was a hiatus).

**Comment by JacksonJN** [comment]
Thanks for the info.
