### PR TITLE
Exit process with error on bundler errors (#2240)

### LINKED ISSUE #2240: Should missing files fail bundle?
If a file is not found during the build, the bundler logs the error but does not fail or exit the process with an exit code.

## Expected Behavior

exit process with non zero

## Current Behavior

```
File does not exist: /Users/jg/mithril.js/bananas.js
```
Missing file is logged, no failure.

## Possible Solution

If a file is missing, log it, but also exit with an error code.

## Steps to Reproduce (for bugs)

https://github.com/reergymerej/mithril.js/commit/11f6e560400619f411f10ca94eb02c6bd5210df2

1. Import a missing file in `index.js` and `npm run build`.

## Context

I was just exploring and fat-fingered something.  This is a question for the maintainers.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

### PR DESCRIPTION
**Pull request by reergymerej**
## Description

Setting the errorCode within bundle.js does not change the exit code
when called with cli.js.  This moves the outer `try...catch` from
bundle.js to the `bundle` call in cli.js, so it can set the exit code.

## Motivation and Context

fixes #2240 

## How Has This Been Tested?

I tested this manually by changing an import path in `index.js` and running the bundler manually and with npm:
```
node bundler/cli.js browser.js -output mithril.js; echo $status
File does not exist: /Users/jg/code/personal/mithril.js/requestx.js
1

npm run build-browser
...
File does not exist: /Users/jg/code/personal/mithril.js/requestx.js
...
npm ERR! errno 1
``` 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I have updated `docs/change-log.md`

### CODE REVIEW

**Comment by reergymerej** [comment]
I created the PR before fixing the whitespace.  Please let me know if you'd like me to squash these or change anything.

File: bundler/cli.js [hunk 1]
```diff
@@ -24,7 +24,13 @@ function add(value) {
 	command = null
 }
 
-bundle(params.input, params.output, {watch: params.watch})
+try {
+	bundle(params.input, params.output, {watch: params.watch})
```
Comment (isiahmeadows) [inline bundler/cli.js]: Better idea: let's just not catch it (i.e. rip out the `try`/`catch` altogether). If we can't create the bundle in the first place, why should we try to minify it?

**Comment by isiahmeadows** [comment]
And BTW, I can always squash it on my end.

(BTW, the failing build is because of a flake that needs a timeout increased I suspect.)
