### PR TITLE
Handle `[` fragment selector. Fixes #2349

### LINKED ISSUE #2349: `m()` should be able to tolerate `"["` as a tag and do the right thing about it.
## Expected Behavior

`m("[", attrs, ...children)` should be equivalent to `m.fragment(attrs, ...children)`

## Current Behavior

Mithril treats it like a DOM element, which is obviously the wrong thing to do here.

## Possible Solution

Add `&& selector !== "["` to [this condition](https://github.com/MithrilJS/mithril.js/blob/next/render/hyperscript.js#L92) and duplicate [all the basic fragment tests](https://github.com/MithrilJS/mithril.js/blob/next/render/tests/test-fragment.js) to check that it works equivalently with `m("[", ...)` (you could just wrap all the tests in a factory that is passed both `m.fragment` and `function () { return m.apply(null, ["["].concat(arguments)) }` to create the fragment. Yes, it's *that* simple.

## Steps to Reproduce

1.
2.
3.
4.

## Context

It makes it basically impossible to use `pragmaFrag: "'['"`/`/* @jsxFrag '[' */` with Babel (which [does actually work](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PQKhAIAECsGcA9wFtwmAKFBGCBiAnAQwHNwByAbTNQ3QEskAHAe3wBdlwAzfZlAIiR02AC3x0ANv3ToApvBbtwAE1ldCAVwkcA3unDgAbnVkB3AFzgAFAEpwAXgB84ADyPRdWOE_hC4NrKwbC7AjgA06AC-QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.1.6&envVersion=))

<details>
  <summary>Additional Information</summary>

## Your Environment

* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:
</details>

### PR DESCRIPTION
**Pull request by vrimar**
## Description
Handles `[` fragment selector.

## Motivation and Context
Fixes [2349](https://github.com/MithrilJS/mithril.js/issues/2349).

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have updated `docs/change-log.md`

### CODE REVIEW

File: render/tests/test-fragment.js [hunk 1]
```diff
@@ -2,196 +2,208 @@
...
-			o(vnode.children[0].children).equals(0)
+var m = require("../../render/hyperscript")
+
+function fragmentStr() {
+	var args = [].slice.call(arguments);
+	args.unshift("[");
+	return m.apply(null, args)
+}
+
+function runTest(name, fragment) {
```
Comment (isiahmeadows) [inline render/tests/test-fragment.js]: Could you instead do something like this, with it all as nested specs?

```js
o.spec("fragment", function () {
	function runTest(name, fragment) {
		// ...
	}

	runTest("m.fragment()", fragment)
	runTest("m('[')", function() {
		var args = [].slice.call(arguments)
		args.unshift("[")
		return m.apply(null, args)
	})
})
```

This way, you're not introducing another global - these are currently running globally in the browser. It also makes for slightly nicer test names. (I plan to clean up the global issue eventually, but I'd like it to work as-is for now.)
