### PR TITLE
Handle newlines in error messages, fixes #1495

### LINKED ISSUE #1495: [ospec] newlines in error messages confuse the error reporter
### Description:

The presence of newlines in error messages cause a line of said message to be displayed instead of the stack trace

### Steps to Reproduce:

https://runkit.com/58603d35d1b6b10013e1e652/58603d36d1b6b10013e1e653

### PR DESCRIPTION
**Pull request by RodericDay**
## Description
Moves an inline `match` call into its own function (`o.fn` level), adds a failing test to that function, then fixes its behavior.

## Motivation and Context
Fixes #1495 

## How Has This Been Tested?
Created a new function, ran `node ospec/bin/ospec` on it

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [~] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have updated `docs/change-log.md`

### CODE REVIEW

File: ospec/ospec.js [hunk 1]
```diff
@@ -49,6 +49,9 @@ module.exports = new function init(name) {
 		spy.callCount = 0
 		return spy
 	}
+	o.cleanStackTrace = function(stack) {
+		return stack.match(/^(?:(?!Error|[\/\\]ospec[\/\\]ospec\.js).)*$/gm).pop()
```
Comment (isiahmeadows) [inline ospec/ospec.js]: Not a critical nit, but this isn't safe for if `ospec` is bundled. (This isn't a problem for Mithril, but some of its users might get tripped up on it.)

Comment (RodericDay) [reply ospec/ospec.js]: I... don't really get it. I just placed that funtion there cause I wanted to have it accessible in the test, but still encapsulated within the o object. I'd happily move it.

Comment (isiahmeadows) [reply ospec/ospec.js]: To clarify, the code snippet I'm referring to was there originally.

**Comment by isiahmeadows** [comment]
Merging, since this seems to have fallen through the cracks...
