### PR TITLE
Fix #2192

### LINKED ISSUE #2192: Allow CSS vars to be specified via `style` attribute
## Steps to Reproduce
[In this example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvLfAJ3oBMZmAKNy8gVxy18AI0psAniQAEyADppp0rFwDkI-jRrVVM4HBoTYiacFUBac1SiVmqk6oBMAVmcyADB9UBfbzNUASjBsAISqAJQkCkoq6praaLqmBkYwJmaW1rb20qqe0vkuzj5+uQBCUPwwYZHR0nWxIna1ivWtjfE6etTkrBh0JgBu0gC8AHzSg-i8TCmw+HAwNAAKzJQADpyGapmUNnb+RR5e4aWBwTVR7WoaWl2mPX0Dk6MTUzMLhvOLK2ubzNsLFY9tl-PlCq4ImcKlVLgoALrhEBkRawcg0CDUBCIEDuRAuEB+dDYXA4-DkOCkCjUOgMHG3BKmOoiDDkADWAHM1vw0GwTMwOSyuIMMNxdvtIgV8ABmcIAbjqWWYJiUqoFQpFYuBEpkAEZ8O55XU2BA4OsoBgJCqlBA0FBbTBzCIbOyFa11hg2Ca0BzrVLnDAsG6lGJmBxlaqlLr1gAPaRwPYQNhu7zIkComDozFobG4xAADkJ8LI9rQbOxqBAmBwjAgNAAFsxoGn+MwoHh61p1nBEAB6Xs89ac8mULC9rB1xvQAAC+v1ADZx5Om1AiFTDJs8HBehB1jQi94gA)…

## Expected Behavior
The first line of buttons should appear the same as the second.

## Current Behavior
The first line of buttons do not have the CSS variable declarations applied, because CSS variables must be declared via `setProperty`

## Possible Solution
[Use the explicit `style.getPropertyValue` & `style.setProperty` APIs](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables#Values_in_JavaScript) instead of [treating `style` as a POJO to be assigned to](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L777-L781)

### PR DESCRIPTION
**Pull request by barneycarroll**
## Description
[Use the property access methods of the CSS style declaration object](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration#Syntax).

## Motivation and Context
Allows CSS vars to be declared in hyperscript as per #2192

## How Has This Been Tested?
Hand-testing 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have updated `docs/change-log.md`

### CODE REVIEW

File: render/tests/test-updateElement.js [hunk 1]
```diff
@@ -179,19 +179,6 @@ o.spec("updateElement", function() {
 		o(updated.dom.style.backgroundColor).equals("red")
 		o(updated.dom.style.border).equals("")
 	})
-	o("updates style when it's same object but mutated", function() {
```
Comment (isiahmeadows) [inline render/tests/test-updateElement.js]: Could you reinstate this test and just test for the opposite (that it *doesn't* update)?

Comment (barneycarroll) [reply render/tests/test-updateElement.js]: I'm not sure it's a good idea to write tests to validate undefined behaviour. Not respecting mutations is something we warn against at a high level, but it's not something we should be asserting enforcements for at every level.

**Comment by isiahmeadows** [comment]
LGTM. Let's land this and see if it breaks anyone.
