### PR TITLE
Fix form checkValidity(), remove vnode.dom === .activeElement from setAttr() (Continued from #2257)

### LINKED ISSUE #2256: Form checkValidity() sometimes returns true when form fields are invalid
When using [`m.withAttr()` to maintain an `input` `value`](https://github.com/MithrilJS/mithril.js/blob/next/docs/withAttr.md#description), the form's `checkValidity()` method sometimes returns `true` when form fields are not valid. This happens on the second and subsequent submissions.

## Expected Behavior

`checkValidity()` should always return `false` if any fields within the `form` aren't valid, eg: https://codepen.io/kevinkace/pen/rqKroe?editors=1011

## Current Behavior

`checkValidity()` returns `true` when a field contains an invalid `value`, on the second and subsequent submits. eg: https://codepen.io/kevinkace/pen/XxYBoK?editors=0011

## Steps to Reproduce (for bugs)

https://codepen.io/kevinkace/pen/XxYBoK?editors=0011

1. use `m.withAttr()` to set the `value` of an `input` with a `minlength`, eg:
```js
m("input", {
  minlength : 4,
  value : vnode.state.value,
  oninput : m.withAttr("value", function(value) {
    vnode.state.value = value;
  }
})
```
2. add an `onsubmit` handler to the `form` element, eg:
```js
m("form", {
  oncreate : function(formVnode) {
    vnode.state.formDom = formVnode.dom;
  },
  onsubmit : function(e) {
    e.preventDefault();
    vnode.state.formDom.checkValidity();
  },
  // form elements...
)
```
3. add a `button` to the form, eg `m("button", "submit")`
4. add 3 characters to the input
5. click the `button`, `checkValidity()` should return `false`
6. click the `button`, `checkValidity()` now returns `true`

## Context

I'm trying to used HTML form validation for form submition.

## Your Environment

* Version used: 1.1.6
* Browser Name and version: Chrome 70, Firefox Quantum 62
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: https://github.com/kevinkace/lyrite/tree/firebase (code of issue isn't yet submitted)

### PR DESCRIPTION
**Pull request by kfule**
Remove vnode.dom === activeElement(vnode.dom) from setAttribute() to fix validityCheck(), to fix https://github.com/MithrilJS/mithril.js/issues/2256

## Description

This is #2257 reopened. (#2257 is for the `next` branch and may not be reopened as is.)
I cherry-picked commit #2257 with additional comments and refactoring.

## Motivation and Context

It appears that #2257 was incorrectly closed due to a typo (with 2557, https://github.com/MithrilJS/mithril.js/pull/2257#issuecomment-2599762079).
#2257 actually fixes #2256.

## How Has This Been Tested?

- `npm run test`
- The following flems were tested using this PR build bundle.
[flems (input)](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5YxAARhaAJywUJENAAcArsQDcAHTQ6s+LLVUMAFABNa1VTgb4ARrTMBPBcB0SJ9ajJgZGJgDc0RxgASgk3NA8PaTkJAF4JIJD8CyxtKIl2dySIGAB3QOCzMIicjx9iVRkorBMtcFksBtdy6I9ggIwoCDM-GAlECWIZVRgKNvb6OFU7LAhiE1LI9tWJGHxlHwCRABEYMAxVKEXQjLX2ydXqQhhqAGsTM6uPVivszPa6hqU1Yhayp9VsQnMoBkMGowAB7-SgvJLdMaDJLFDZwYj9fBdKBjCZAr5KWBoADmxEIyIALHiLhIfABHVQQHxmZEjXHw+i-dTIpbheIAPkBNI8yRK+HRmOxSMSGwxMmJMGIWMRMHOwpud0ez3x0Q+NK8Pn6Ji5xAAaqjwithSaEooVOpzSk0mq1m8daxQtTVt8QHZ1MR6ADgMNQeCJA0ZnMFg0sgoI7N5rDQm1ta8dB6MjowMZqMQIPQJBqHk8hYXprRYPgoLRiSYAAYB2gAZUIsmIQwAJMATcqemYFk58I2W23WHWvcLonWpTAALIQOBwJTEzvd+1K7G9Ae9sbzxfLscTycSOtF+6m7pbkGr2L6M8XvsDp5jnLat06SggOAwWC5-NoBAeAAJgAZkQABONgOBATAcDwfBqEXT8hEYZgeDYABdKgejQe5ANQGCuDwRNCBkaBP2qcgeBIYhlDgRAAHoGOMZR7mJBDaCwBiSLIqAAAEgPwQSAEYgO4hZSOgAwlHwfhPxBME8DgbwIGUURWAw1ggA)
[flems (textarea)](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5YxAARhaAJywUJENAAcArsQDcAHTQ6s+LLVUMAFABNa1VTgb4ARrTMBPBcB0SJ9ajJgZGJgDc0RxgASgk3NA8PaTkJAF4JIJD8CyxtKIl2dySIGAB3QOCzMIicjx9iVRkorBMtcFksBtdy6I9ggIwoCDM-GAlECWIZVRgKNvb6OFU7LAhiE1LI9tWJGHxlHwCRABEYMAxVKEXQjLX2ydXqQhhqAGsTM6uPVivszPa6hsYAD2IMD4MC0yp9Vl0oGNBklihs4ADGPgIWMJmCvkpYGgAObEQjQgAsqIuEh8AEdVBAfGZoSMUS9PGglGpJEMluF4gA+UHEjzJEr4eH9JHdKGJDYAmRYmDEYWQmDnHk3O6PZ5o6IfYleIH+JnqABqsPCKx5uskiVNBpSaQVazeatYoSJq2+IDs6mI9BBwGGTmUAyGDRmcwWDSyCkDs3mxAaoTaqteOgdGR0YGM1GIEHoEiVDye3Oz01osHwUFoWJMAAMPbQAMqEWTEIYAEmAptlvQWTnw1brDdYFadPOiFeRMAAshA4HAlFjm62VOp22ZO7KxhOpzP+4OhxIKzn7nruh3iE457F9PvDz1lyenv2cqq7TpKCA4DBYOnM2gEDwAIwANkQAAGNgOBATAcDwfBqCnF8hEYZgeDYABdKgejQe4f1QcCuDwKNCBkaAX2qcgeBIYhlDgRAAHpqOMZR7ixaDaCwaj8MIqAAAEACZ8F439uLYhYCOgAwlHwfgXxPP08DgbwIGUURWGQ1ggA)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] My change requires a documentation update, and I've opened a pull request to update it already:
- [x] I have read https://mithril.js.org/contributing.html.

### CODE REVIEW

**Comment by kfule** [comment]
Please let me know if any additional test code is needed.
In my opinion, it seems difficult to reproduce the behavior of checkValidity() using domMock for testing.

File: render/render.js [hunk 1]
```diff
@@ -684,17 +684,17 @@ module.exports = function() {
 			if (key === "value") {
 				// Only do the coercion if we're actually going to check the value.
 				/* eslint-disable no-implicit-coercion */
-				var isFileInput = vnode.tag === "input" && vnode.attrs.type === "file"
 				//setting input[value] to same value by typing on focused element moves cursor to end in Chrome
 				//setting input[type=file][value] to same value causes an error to be generated if it's non-empty
-				if ((vnode.tag === "input" || vnode.tag === "textarea") && vnode.dom.value === "" + value && (isFileInput || vnode.dom === activeElement(vnode.dom))) return
+				//setting input[value] to same value sometimes causes checkValidity() to return true when form fields are invalid(#2256)
```
Comment (dead-claudia) [inline render/render.js:689]: The precise issue is this: `minlength` and `maxlength` constraints in form controls are only checked against values generated from user edits, not from script edits. When a user edits it and a script reads and writes the same previous value, the current value is considered to be last edited by script, and thus `minlength` and `maxlength` constraints are no longer checked.

I'll leave it to you how to distill this into a comment. Here's the relevant spec links:

- https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-maxlength
- https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-minlength

**Review by dead-claudia — CHANGES_REQUESTED** [review]
Verified by mirroring the changes in your input and textarea examples.

[I would like to see a manual render test](https://github.com/MithrilJS/mithril.js/tree/main/render/tests/manual) at minimum, though. Here's some smaller test cases for you:

- [input](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5YxAAQQ0ABwCuxChIBuGKHJgBuADppdWfFlpyGACgAmtanJwN8AI1rmAnkuC6JKiDADuiCaYAlBIAvAB8EsgenlKyCqESWKbaINLyxClu0TESxM4yMP4pjAAeGZTZMarqMBSVnljSADJMAObEhP4ALHVoOZ4ATjAAjnIQQ+b+xAMavf0S9GkKpjDB7n3zKmoaCTD4xBgDrTDE+NUaOhvz1IQw1ADWQZfzrJWsgXMxSSn2CsT0mQk63m9GoUAgDxWa3qMRud0egWe-VeVwk7AkKTgcnsjXKgWiAF1eu9LrowCZqMQIPQJHDIdCNkI4LRYPgoLRWqYAAb-WgAZUItAGxH8ABJgEtTpYDNUIOYIHl9rR+YLhawuZ9Nv0uecYABZCBwODSVpiiVxKW0GVqOUK5xnbb6w3GtCtdWarUxLl0+4ANRt8ryZsl+Gl+B9-vBgecQXV0URuhRlBAcBgsEp1LQCB4XUQAEYAKwAWlzACYAAxsDggTA4PDho3JoSMZg8NhEkDgtD3bOoGtcPC4wgDaDJuQDcg8EjEGRwRAAennJhk91a4at86HI6gAAFS-h93nS5uFcPoIZpPh+Mm8gU8HBqCOZKJWATWEA)
- [textarea](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5YxAAQQ0ABwCuxChIBuGKHJgBuADppdWfFlpyGACgAmtanJwN8AI1rmAnkuC6JKiDADuiCaYAlBIAvAB8EsgenlKyCqESWKbaIIwAHsQYAE4wGClu0TEqahoUhTFY0gAyTADmxIT+ACxlaEWeOQCOchA55v7EWaXlnvTS8sSmMMHube2equowCTD4mVm1MMT4ixo6c-PUhDDUANZB+-Os5ayBrUVJKfYKxPT5ErPz9NRQEGdTMxGMSOJ3OgUu7WuBwk7AkKTgcnslWIKUC0QAuq1bvtdGATNRiBB6BIQf9AXMhHBaLB8FBaLVTAADV60ADKhFoWWI-gAJMBxgp8JYDIsIOYIMRnGtaGyOVzWIz7vNlYzdjAALIQOBwaS1Xn8uLbYU7NRiiVStWa7W6hVK5XtRmk04ANVN4sl+oFRtoBidrt+7ucQQV0XBuihlBAcBgsAJRLQCB4TUQACYAOxsDggTA4PD4ajayNCRjMHhsTEgX5oU6J1DZrh4ZGELLQSNyLLkHgkYgyOCIAD0-ZMMlOtXzPv7TZbUAAAin8POAIwpycS5vQQzSfD8SOSmTcKPUFsyUSsdGsIA)

I couldn't get the `minlength` constraint to work because [it's specified to only validate user input, not script input](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-minlength). I tried instead just doing `<input type="url">` as it's possible to force constraint errors that way, but I couldn't trigger the bug.

Unfortunately, what's really going on is a counterintuitive interaction I've explained in a comment, and unless you feel like wiring up Puppeteer and everything, there's no real way to test this without some exceptionally awkward mocking.

**Comment by kfule** [comment]
@dead-claudia 
Thanks for your kind review comments.
As you suggested, I will add some manual rendering tests and change the comments to be more accurate.

**Review by dead-claudia — APPROVED** [review]

**Review by dead-claudia — APPROVED** [review]

**Review by dead-claudia — APPROVED** [review]

**Comment by dead-claudia** [comment]
Sorry for the noise. Didn't realize the merge rule was stopping me over my comment edit.
